export const robot = [
    {
        id:1,
        name:'Aniruddha',
        username:'ani',
        email:'aniruddha.murthy1@gmail.com'
    },
    {
        id:2,
        name:'Akhilesh',
        username:'akhi',
        email:'nsakhilesh@gmail.com'
    },
    {
        id:3,
        name:'Anirudh',
        username:'jakati',
        email:'anirudh.rj97@gmail.com'
    },
    {
        id:4,
        name:'Anirban',
        username:'ghosh',
        email:'mailtoanirban@gmail.com'
    },
    {
        id:5,
        name:'Raksha',
        username:'Rao',
        email:'rakfeb18@gmail.com'
    },
    {
        id:6,
        name:'Disha',
        username:'Khanted',
        email:'disha.khanted@gmail.com'
    },
]